package id.ac.poliban.mi.andre.makanannusantara;

import java.util.ArrayList;
import java.util.List;

public class FoodData {
    static List<Food> getFoodList() {
        List<Food> data = new ArrayList<>();
        {
            data.add(new Food("https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Nasi_Gudeg.jpg/220px-Nasi_Gudeg.jpg", "Gudeg", "Gudeg (ejaan bahasa Jawa: ꦒꦸꦝꦼꦒ꧀\u200B, Gudheg) adalah makanan khas Yogyakarta dan Jawa Tengah yang terbuat dari nangka muda yang dimasak dengan santan. Perlu waktu berjam-jam untuk membuat masakan ini. Warna coklat biasanya dihasilkan oleh daun jati yang dimasak bersamaan. Gudeg dimakan dengan nasi dan disajikan dengan kuah santan kental (areh), ayam kampung, telur, tempe, tahu dan sambal goreng krecek."));
            data.add(new Food("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Pecel_Hariadhi.JPG/220px-Pecel_Hariadhi.JPG", "Pecel", "Pecel atau pecal (Hanacaraka: ꦥꦼꦕꦼꦭ꧀) merupakan makanan yang dikombinasikan dengan bumbu sambal kacang sebagai bahan utamanya dan dicampur dengan aneka jenis sayuran. Makanan ini populer terutama di wilayah DI Yogyakarta, Jawa Tengah, dan Jawa Timur."));
            data.add(new Food("https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Lumpia.JPG/257px-Lumpia.JPG", "Lumpia", "Lumpia atau terkadang dieja sebagai lun pia (Hanzi: 潤餅 / 润饼, POJ: lūn-piáⁿ, hanyu pinyin: rùn bǐng, Bahasa Inggris: long pia) adalah sejenis jajanan tradisional Tionghoa. Lumpia yang dikenal oleh orang Indonesia merupakan lafal Bahasa Hokkian."));
            data.add(new Food("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Ketupat2.jpg/250px-Ketupat2.jpg", "Ketupat", "Ketupat atau kupat (Jawi: کتوڤت; Jawa: ꦏꦸꦥꦠ꧀, kupat) adalah hidangan khas Asia Tenggara maritim berbahan dasar beras yang dibungkus dengan pembungkus terbuat dari anyaman daun kelapa muda (janur), atau kadang-kadang dari daun palma yang lain. Ketupat paling banyak ditemui pada saat perayaan Lebaran sampai 5 hari berikutnya ketika umat Islam merayakan berakhirnya bulan puasa."));
            data.add(new Food("https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Sate_Ponorogo.jpg/220px-Sate_Ponorogo.jpg", "Sate", "Sate (ejaan KBBI: satai) adalah makanan yang terbuat dari daging yang dipotong kecil-kecil dan ditusuk sedemikian rupa dengan tusukan lidi tulang daun kelapa atau bambu kemudian dipanggang menggunakan bara arang kayu. Sate disajikan dengan berbagai macam bumbu yang bergantung pada variasi resep sate.[1] Daging yang dijadikan sate antara lain daging ayam, kambing, domba, sapi, babi, kelinci, kuda, dan lain-lain."));
            data.add(new Food("https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Rendang_daging_sapi_asli_Padang.JPG/250px-Rendang_daging_sapi_asli_Padang.JPG", "Rendang", "Rendang atau randang (Jawi: رندڠ) adalah masakan daging dengan bumbu rempah-rempah yang berasal dari Minangkabau. Masakan ini dihasilkan dari proses memasak yang dipanaskan berulang-ulang menggunakan santan sampai kuahnya kering sama sekali. "));
            data.add(new Food("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Made%27s_Warung_Nasi_Campur.jpg/220px-Made%27s_Warung_Nasi_Campur.jpg", "Nasi Campur", "Nasi campur adalah masakan khas Indonesia.[1] Makanan ini terdiri dari nasi putih yang dihidangkan dengan bermacam-macam lauk-pauk. Lauk yang digunakan adalah sambal goreng, abon, serundeng, tahu goreng, ikan goreng, telur dan lain-lain."));
            data.add(new Food("https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Soto_Betawi.jpg/257px-Soto_Betawi.jpg", "Soto", "Soto, sroto, sauto, tauto, atau coto adalah makanan khas Indonesia seperti sop yang terbuat dari kaldu daging dan sayuran. Daging yang paling sering digunakan adalah daging sapi dan ayam, tetapi ada pula yang menggunakan daging babi atau kambing. Berbagai daerah di Indonesia memiliki soto khas daerahnya masing-masing dengan komposisi yang berbeda-beda."));
            data.add(new Food("https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/MartabakManis.JPG/280px-MartabakManis.JPG", "Kue Terang Bulan", "Kue terang bulan adalah penganan sejenis panekuk yang biasa dijajakan di pinggir jalan di seluruh Indonesia dan Malaysia, khususnya Sabah. Juga dikenal sebagai apam pulau pinang atau martabak manis/martabak bangka (Jakarta), terang bulan (Bandung), dll."));
            data.add(new Food("https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Nasi_uduk.jpg/220px-Nasi_uduk.jpg", "Nasi Uduk", "Nasi uduk atau dalam bahasa Belanda Rijst vermengd met onrust van de liefde atau disingkat Jaloerse rijst adalah nama makanan yang terbuat dari bahan dasar nasi putih yang diaron dan dikukus dengan santan, serta dibumbui dengan pala, kayu manis, jahe, daun serai dan merica. Makanan ini ditemukan oleh penduduk pulau Jawa sekitar tahun 1910-1924 dan dipopulerkan oleh Hindia Belanda setelahnya."));
            data.add(new Food("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Cendol_in_a_Glass.JPG/220px-Cendol_in_a_Glass.JPG", "Es Cendol", "Cendol merupakan minuman khas Sunda yang dahulunya terbuat dari tepung hunkwe, namun kini cendol terbuat dari tepung beras, disajikan dengan es parut serta gula merah cair dan santan. Rasa minuman ini manis dan gurih. "));
        }
        return data;
    }
}
